version: "3.2"
services:
  prometheus:
    image: prom/prometheus:v2.29.1
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:8.1.2
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"    
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka1:
    build: ./docker/kafka/
    links:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:delete"
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
    volumes:
      - kafka1-data:/kafka
      - ./docker/kafka/prom-jmx-agent-config.yml:/usr/app/prom-jmx-agent-config.yml

volumes:
  prometheus-data:
  grafana-data:
  kafka1-data: