version: "2.2"
services:
  # https://ci.apache.org/projects/flink/flink-docs-stable/docs/deployment/resource-providers/standalone/docker/#flink-with-docker-compose

  jobmanager:
    build:
      context: ./flinkApp/
    ports:
      - "8081:8081"
    command: standalone-job --job-classname autheventsanalyse.JobStarter
    #volumes:
    #  - ./flinkApp/authEventsAnalyse/target/authEventsAnalyse-0.1.jar:/opt/flink/usrlib/authEventsAnalyse-0.1.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2

  taskmanager:
    build:
      context: ./flinkApp/
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    #volumes:
    #  - ./flinkApp/authEventsAnalyse/target/authEventsAnalyse-0.1.jar:/opt/flink/usrlib/authEventsAnalyse-0.1.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2

  ml-api:
    build:
      context: ./python-ml-api/
    volumes:
      - ./jupyter-ml-training/workspace/model/RiskyAuthenticationEventPredictionWithRandomForestClassifier.joblib:/program/RiskyAuthenticationEventPredictionWithRandomForestClassifier.joblib
    ports:
      - "5000:5000"

  flink-sql-api:
    image: romainr/flink-sql-api:1.11.1
    container_name: flink-sql-api
    ports:
      - "8083:8083"
    depends_on:
      - jobmanager

  hue:
    image: romainr/hue:demo-streams-v3
    hostname: hue
    container_name: hue
    ports:
      - "8888:8888"
    depends_on:
      - hue-database
    command: ["./wait-for-it.sh", "hue-database:3306", "--", "./startup.sh"]

  hue-database:
    image: mysql:5.7
    container_name: hue-database
    ports:
      - "33061:3306"
    volumes:
      - hue-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: hue
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: hue

volumes:
  hue-data: