version: "2.2"
services:
  # https://ci.apache.org/projects/flink/flink-docs-stable/docs/deployment/resource-providers/standalone/docker/#flink-with-docker-compose

  jobmanager:
    build:
      context: ./flinkApp/
    ports:
      - "8081:8081"
    command: standalone-job --job-classname autheventsanalyse.JobStarter
    #volumes:
    #  - ./flinkApp/authEventsAnalyse/target/authEventsAnalyse-0.1.jar:/opt/flink/usrlib/authEventsAnalyse-0.1.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2

  taskmanager:
    build:
      context: ./flinkApp/
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    #volumes:
    #  - ./flinkApp/authEventsAnalyse/target/authEventsAnalyse-0.1.jar:/opt/flink/usrlib/authEventsAnalyse-0.1.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2

  ml-api:
    build:
      context: ./python-ml-api/
    volumes:
      - ./jupyter-ml-training/workspace/model/RiskyAuthenticationEventPredictionWithRandomForestClassifier.joblib:/program/RiskyAuthenticationEventPredictionWithRandomForestClassifier.joblib
    ports:
      - "5000:5000"